---
# This role installs NGINX and configures it.
- include_vars: secrets.yml

# # LetsEncrypt CertBot
# - name: Add Certbot apt repo
#   apt_repository:
#     repo: ppa:certbot/certbot

# - name: Update apt cache
#   apt: update_cache=yes

# - name: Install Certbot
#   apt:
#     name: python-certbot-nginx
#     state: present

# # NGINX
# - name: Install nginx
#   apt:
#     name: nginx
#     state: present
# - name: Copy nginx config
#   template:
#     src: nginx.conf
#     dest: /etc/nginx/nginx.conf
#     owner: www-data
#     group: www-data
#     mode: 0644
# - name: Copy nginx SSL params
#   template:
#     src: ssl-params.conf
#     dest: /etc/nginx/ssl-params.conf
#     owner: www-data
#     group: www-data
#     mode: 0644
# - name: Copy .htpasswd
#   template:
#     src: .htpasswd
#     dest: /etc/nginx/.htpasswd
#     owner: www-data
#     group: www-data
#     mode: 0644
- name: Copy website config
  template:
    src: website
    dest: /etc/nginx/sites-available/website
    owner: www-data
    group: www-data
    mode: 0644
- name: Symlink website config
  file:
    src: /etc/nginx/sites-available/website
    dest: /etc/nginx/sites-enabled/website
    owner: www-data
    group: www-data
    state: link
- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Restart nginx
  service:
    name: nginx
    state: restarted
