---
# This role installs PostgreSQL and configures it.
- include_vars: secrets.yml

# Postgres
- name: Install PostgreSQL
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
    - python-psycopg2
- name: Copy postgresql config
  template:
    src: postgresql.conf
    dest: /etc/postgresql/9.5/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
- name: Copy postgres hosts config
  template:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640

- include_tasks: setup_db.yml
  loop_control:
    loop_var: db
  with_items:
    - name: whatson
      owner: "{{ db_user_whatson }}"
      password: "{{ db_password_whatson }}"
    - name: photos
      owner: "{{ db_user_photos }}"
      password: "{{ db_password_photos }}"
    - name: links
      owner: "{{ db_user_links }}"
      password: "{{ db_password_links }}"
    - name: war
      owner: "{{ db_user_war }}"
      password: "{{ db_password_war }}"

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
