---
# This role installs PostgreSQL and configures it.
- include_vars: secrets.yml

# Postgres
- include_tasks: setup_db.yml
  loop_control:
    loop_var: db
  with_items:
    - name: photos
      owner: "{{ db_user_photos }}"
      password: "{{ db_password_photos }}"
    - name: links
      owner: "{{ db_user_links }}"
      password: "{{ db_password_links }}"
    - name: reader
      owner: "{{ db_user_reader }}"
      password: "{{ db_password_reader }}"
    - name: wombat
      owner: "{{ db_user_wombat }}"
      password: "{{ db_password_wombat }}"
