---
# Common config
- include_vars: secrets.yml

- name: Update apt cache
  apt: update_cache=yes

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
- name: Copy fail2ban config
  template:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

# Secrets / parameterized config
- name: Write envar {{ item.key }}
  lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}"
    line: '{{ item.key }}="{{ item.value }}"'
  loop:
    - key: SENDGRID_API_KEY
      value: "{{ sendgrid_api_key }}"
    - key: STRIPE_API_KEY
      value: "{{ stripe_api_key }}"
    - key: AWS_ACCESS_KEY_ID
      value: "{{ aws_access_key_id }}"
    - key: AWS_SECRET_ACCESS_KEY
      value: "{{ aws_secret_access_key }}"
    - key: DJANGO_SECRET_KEY
      value: "{{ django_secret_key }}"
    - key: GOOGLE_OAUTH2_KEY
      value: "{{ google_oauth_2_key }}"
    - key: GOOGLE_OAUTH2_SECRET
      value: "{{ google_oauth_2_secret }}"
    - key: FACEBOOK_KEY
      value: "{{ facebook_key }}"
    - key: FACEBOOK_SECRET
      value: "{{ facebook_secret }}"
    - key: LINKS_REDDIT_CLIENT_ID
      value: "{{ links_reddit_client_id }}"
    - key: LINKS_REDDIT_CLIENT_SECRET
      value: "{{ links_reddit_client_secret }}"
    - key: LINKS_REDDIT_USERNAME
      value: "{{ links_reddit_username }}"
    - key: LINKS_REDDIT_PASSWORD
      value: "{{ links_reddit_password }}"

# App specific config
- include_tasks: setup_app_envars.yml
  loop_control:
    loop_var: app
  with_items:
    - prefix: LINKS
      raven: "{{ links_raven_dsn }}"
      db_user: "{{ db_user_links }}"
      db_password: "{{ db_password_links }}"
      db_host: "167.99.78.141"
      papertrail_hostname: ""
      papertrail_url: ""
      papertrail_port: ""

    - prefix: PHOTOS
      raven: "{{ photos_raven_dsn }}"
      db_user: "{{ db_user_photos }}"
      db_password: "{{ db_password_photos }}"
      db_host: "167.99.78.141"
      papertrail_hostname: "MemoriesNinja"
      papertrail_url: "{{ papertrail_url }}"
      papertrail_port: "{{ papertrail_port }}"

    - prefix: READER
      raven: "{{ reader_raven_dsn }}"
      db_user: "{{ db_user_reader }}"
      db_password: "{{ db_password_reader }}"
      db_host: "167.99.78.141"
      papertrail_hostname: "BlogReader"
      papertrail_url: "{{ papertrail_url }}"
      papertrail_port: "{{ papertrail_port }}"
