version: '3'

services:
    jenkins:
        image: localhost:5000/jenkins
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            # Mount jenkins
            - jenkins_home:/var/jenkins_home
            # Jenkins effectively runs as root on the host
            # if you do this, so be careful!
            - /var/run/docker.sock:/var/run/docker.sock
            - /root/scripts:/var/build/scripts
            - /root/backups:/var/build/backups

        ports:
            - 8080:8080
        environment:
            - SWARM_HOST=167.99.78.141
            # Pass through
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - WHATSON_DB_USER
            - WHATSON_DB_PASSWORD
            - LINKS_DB_USER
            - LINKS_DB_PASSWORD
            - PHOTOS_DB_USER
            - PHOTOS_DB_PASSWORD
            - WAR_DB_USER
            - WAR_DB_PASSWORD

volumes:
    jenkins_home:
