version: '3'

services:
    jenkins:
        image: jenkins/jenkins:lts
        volumes:
            - jenkins_home:/var/jenkins_home
        ports:
            - 8080:8080
        environment:
            FOO: BAR

volumes:
    jenkins_home:
