version: '3'

services:
  concourse-web:
    image: localhost:5000/concourse
    command: web
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes:
        - "./keys/web:/concourse-keys"
        # Concourse  effectively runs as root on the host
        # if you do this, so be careful!
        # - /var/run/docker.sock:/var/run/docker.sock
        # - /root/scripts:/var/build/scripts
        # - /root/backups:/var/build/backups
    environment:
    - "SWARM_HOST=${CONCOURSE_DB_HOST}"
    - "CONCOURSE_POSTGRES_HOST=${CONCOURSE_DB_HOST}"
    - "CONCOURSE_POSTGRES_USER=${CONCOURSE_DB_USER}"
    - "CONCOURSE_POSTGRES_PASSWORD=${CONCOURSE_DB_PASSWORD}"
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=https://concourse.mattslinks.xyz
    - CONCOURSE_MAIN_TEAM_GITHUB_USER=MattSegal
    # # Pass through
    - CONCOURSE_GITHUB_CLIENT_ID
    - CONCOURSE_GITHUB_CLIENT_SECRET
    # # - AWS_ACCESS_KEY_ID
    # # - AWS_SECRET_ACCESS_KEY
    # # - WHATSON_DB_USER
    # # - WHATSON_DB_PASSWORD
    # # - LINKS_DB_USER
    # # - LINKS_DB_PASSWORD
    # # - PHOTOS_DB_USER
    # # - PHOTOS_DB_PASSWORD
    # # - WAR_DB_USER
    # # - WAR_DB_PASSWORD

  concourse-worker:
    image: localhost:5000/concourse
    command: worker
    build:
        context: .
        dockerfile: Dockerfile
    privileged: true
    links: [concourse-web]
    depends_on: [concourse-web]
    volumes:
        - "./keys/worker:/concourse-keys"
    environment:
    - CONCOURSE_TSA_HOST=concourse-web:2222
    - CONCOURSE_GARDEN_NETWORK

