# Example secrets file
---
# Postgress credentials
db_user_tshirt: xxx
db_password_tshirt: xxx
db_user_photos: xxx
db_password_photos: xxx
db_user_links: xxx
db_password_links: xxx
db_user_whatson: xxx
db_password_whatson: xxx
db_user_war: xxx
db_password_war: xxx
db_user_reader: xxx
db_password_reader: xxx

# AWS access
aws_access_key_id: xxx
aws_secret_access_key: xxx

# Google creds
google_oauth_2_key: xxx
google_oauth_2_secret: xxx

# Facebook creds
facebook_key: xxx
facebook_secret: xxx

# Celery flower
flower_user: xxx
flower_password: xxx

# Sentry Logging
photos_raven_dsn: xxx
links_raven_dsn: xxx
whatson_raven_dsn: xxx
reader_raven_dsn: xxx
tshirt_raven_dsn: xxx

# Django session encryption
django_secret_key: xxx

# Whatson special
geocoding_api_key: xxx

# Logging creds
papertrail_url: xxx
papertrail_port: xxx

# Stripe
stripe_api_key: xxx

# Emails
sendgrid_api_key: xxx
